enum SpecializationEnum {
	CARDIOLOGIST,
	DENTIST,
	DERMATOLOGIST,
	ENDOCRINOLOGIST,
	GASTROENTEROLOGIST,
	GYNECOLOGIST,
	NEUROLOGIST,
	OPHTHALMOLOGIST,
	OTOLARYNGOLOGIST,
	ORTHOPEDIST,
	PEDIATRICIAN,
	PSYCHIATRIST,
	RADIOLOGIST,
	SURGEON,
	UROLOGIST,
	VENEREOLOGIST,
	OTHER,
}

export default SpecializationEnum;
