name: continuous integration front

permissions:
  id-token: write
  contents: read

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
  AWS_REGION: eu-central-1
  REMOTE_HOST: n2pz.c.dedikuoti.lt
  REMOTE_USERNAME: root
  REMOTE_KEY: ${{ secrets.KEY }}
  REMOTE_PORT: 22
  REMOTE_PASSPHRASE: ${{ secrets.PASSPHRASE }}

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Run prettier
        run: npx prettier --check .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{env.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{env.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.AWS_REGION}}

      - name: Run script that packages, builds and pushes docker image
        run: |
          sh publish.sh

  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: restart apps
        uses: appleboy/ssh-action@master
        with:
          host: ${{env.REMOTE_HOST}}
          username: ${{env.REMOTE_USERNAME}}
          key: ${{env.REMOTE_KEY}}
          port: ${{env.REMOTE_PORT}}
          passphrase: ${{env.REMOTE_PASSPHRASE}}
          script: |
            sh start.sh
