name: frontend continuous integration

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Run prettier
        run: npx prettier --check .

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build --if-present 

      # - name: Run tests
      #   run: npm run test